### ISSUE TITLE
Cannot trace non-module Go package

### ISSUE THREAD

**Issue by grokify** [izhakjakov/getGoDependencyHierarchy#1]
Go packages without a `go.mod` file are included as `incompatible` in a dependent's `go.mod` file but not traced by the script.

This was covered in the following issue:

https://github.com/grokify/go-aha/issues/1

For example, when tracing `github.com/miekg/dns` from `github.com/grokify/go-aha v0.2.3`, we see the following:

https://github.com/grokify/go-aha/blob/v0.2.3/go.mod

```
〉ggdh 'github.com/miekg/dns'
                     github.com/grokify/go-aha
                                ⬇
                github.com/grokify/gocharts@v1.16.8
                                ⬇
               github.com/blend/go-sdk@v1.20211204.3
                                ⬇
                   github.com/spf13/cobra@v1.1.1
                                ⬇
                   github.com/spf13/viper@v1.7.0
                                ⬇
  github.com/bketelsen/crypt@v0.0.3-0.20200106085610-5cbc8cc4026c
                                ⬇
              github.com/hashicorp/consul/api@v1.1.0
                                ⬇
                 github.com/hashicorp/serf@v0.8.2
                                ⬇
                 github.com/hashicorp/mdns@v1.0.0
                                ⬇
                   github.com/miekg/dns@v1.0.14
```

Specifically, it calls out the following which happens to be incomplete because a non-module Go package is skipped.

```
                github.com/grokify/gocharts@v1.16.8
                                ⬇
               github.com/blend/go-sdk@v1.20211204.3
```

The non-module Go package is `github.com/wcharczuk/go-chart@v2.0.1+incompatible` and the actual dependency tree looks like the following.

```
        github.com/grokify/gocharts@v1.16.3
                        ⬇
 github.com/wcharczuk/go-chart@v2.0.1+incompatible
                        ⬇
       github.com/blend/go-sdk@v1.20211204.3
```

The `github.com/grokify/gocharts@v1.16.3` `go.mod` file looks like the following:

https://github.com/grokify/gocharts/blob/v1.16.3/go.mod

```
module github.com/grokify/gocharts

go 1.16

require (
	github.com/360EntSecGroup-Skylar/excelize v1.4.1
	github.com/blend/go-sdk v1.20211204.3 // indirect
	github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0 // indirect
	github.com/grokify/elastirad-go v0.1.4
	github.com/grokify/mogo v0.32.3
	github.com/jessevdk/go-flags v1.5.0
	github.com/mattn/go-runewidth v0.0.13 // indirect
	github.com/olekukonko/tablewriter v0.0.5
	github.com/pkg/errors v0.9.1
	github.com/valyala/quicktemplate v1.7.0
	github.com/wcharczuk/go-chart v2.0.1+incompatible
	golang.org/x/sys v0.0.0-20211210111614-af8b64212486 // indirect
	google.golang.org/protobuf v1.27.1 // indirect
)
```

Since `github.com/wcharczuk/go-chart v2.0.1` doesn't have a `go.mod` file, it's necessary to get the code and scan it.

I pulled down the code with:

`$ git clone --branch v2.0.1 https://github.com/wcharczuk/go-chart`

and then in ran a quick grep command on `blend` to establish it is used, though a Go parser will want do do more.

**Comment by IzhakJakov** [comment]
I am going to open a feature request for `go mod graph`.  Hopefully they'll be willing to implement this.

**Comment by IzhakJakov** [comment]
https://github.com/golang/go/issues/50656

**Comment by IzhakJakov** [comment]
@grokify would you mind reviewing [PR #3](https://github.com/izhakjakov/getGoDependencyHierarchy/pull/3)?

**Comment by IzhakJakov** [comment]
Hi @grokify is this still an issue?
